# Generated by Django 5.1.5 on 2025-01-23 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0002_customuser_data"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="slug",
            field=models.SlugField(default="", max_length=120),
        ),
    ]
